### ISSUE TITLE
zoom duration conversion to seconds, handle unexpected input

### ISSUE THREAD

**Issue by nataliemona** [harvard-dce/dce-user-analytics#10]
Typically zoom meeting duration comes from the API in the format MM:SS or HH:MM:SS. Found and example (in 10/13/2017 data) of an unexpected format "4 mins" which causes a ValueError.

**Comment by lbjay** [comment]
Working on this now. I found a module, [pytimeparse](https://github.com/wroberts/pytimeparse) that we can fall back to. I'm also going to add a "duration" field to the session records calc'ed from the join/leave times.

**Comment by lbjay** [comment]
Fixed by #11
